name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]+.[0-9]+'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build source
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Test source
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Login to crate.io
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish to crate.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
